---
name: Build weekly
on:
  # enable manual run for debug
  workflow_dispatch:
  schedule:
    # run once a week
    - cron: '0 7 * * 1'

jobs:
  build-examples:
    uses: esp-idf-lib/shared-workflows/.github/workflows/build-weekly.yaml@main
